# Common configuration for all services
server:
  port: ${SERVICE_PORT:8080}

spring:
  application:
    name: ${SERVICE_NAME:waygonway-service}

  data:
    mongodb:
      uri: mongodb://localhost:27017/ticket_reservation_db
      auto-index-creation: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: NON_NULL

logging:
  level:
    com.waygonway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
