server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 30m

spring:
  application:
    name: frontend-service

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /static/**

  web:
    resources:
      static-locations: classpath:/static/

# Logging
logging:
  level:
    com.frontend: DEBUG
    org.springframework.web: INFO
    root: INFO
